# -*- coding: utf-8 -*-
"""code7.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_WeQh_XJcOa58DJEI5lS3sj9t1IRfgN
"""

list=[1,2,3,4,5]
for el in list:
  print(el)

list=[1,4,9,16,25,36,49,64,81,100]
for el in list:
  print(el)

for i in range(1,101):
  print(i)

for i in range(100,0,-1):
  print (i)

num=int(input("enter the number"))
for i in range(1,11):
  print(i*num)

